stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - # Add build commands here, e.g., npm install

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - # Add test commands here, e.g., npm test

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - # Add deployment commands here
  only:
    - main
